name: flutter_instagram_clone
description: The Instagram Clone with Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-285.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
   - assets/svg/instagram.svg
   - assets/svg/reels.svg
   - assets/svg/sent.svg
   - assets/svg/comment.svg
   - assets/images/profile.jpg
   - assets/images/p1.jpg
   - assets/images/p2.jpg
   - assets/images/p3.jpg
   - assets/images/p4.jpg
   - assets/images/messenger.png
   - assets/images/more.png
   - assets/images/post1.jpg
   - assets/images/post2.jpg
   - assets/images/post3.jpg
   - assets/images/post4.jpg
   - assets/images/post5.jpg

